### ISSUE TITLE
Use a top level variables file

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt-ansible#115]
The goal of a top level variables file is to provide the user with a single file that lists the top level variables of kubevirt-ansible.  The variables are mostly playbook level variables that will have a significant impact on how playbooks will run.  Some variables listed here can also be variables that users are likely to change or variables we want a user to be aware of.

```yaml
### Cluster ###
cluster: openshift
namespace: kube-system

### KubeVirt ###
manifest_version: release
docker_tag: latest

### Storage ###
enable_cinder_ceph: false
enable_gluster: false
```
