### ISSUE TITLE
Deployment via APB is failing for 0.7.0-alpha.4

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt-ansible#302]
```
  - containerID: docker://93d0bf9569b06565c4d5d97ee4ab890b3b01b7831786ae71e06d0aeb303ddc6a
    image: docker.io/kubevirt/virt-api:v0.7.0-alpha.4
    imageID: docker-pullable://docker.io/kubevirt/virt-api@sha256:be158f8b49b155094ea602850aab7be853fc64c24680e21b284ede27f0362704
    lastState:
      terminated:
        containerID: docker://93d0bf9569b06565c4d5d97ee4ab890b3b01b7831786ae71e06d0aeb303ddc6a
        exitCode: 127
        finishedAt: 2018-06-26T13:06:28Z
        message: |
          oci runtime error: container_linux.go:247: starting container process caused "exec: \"/virt-api\": stat /virt-api: no such file or directory"
        reason: ContainerCannotRun
        startedAt: 2018-06-26T13:06:28Z
```

cc @rthallisey
